"""In-memory product repository implementation."""

from __future__ import annotations

from models.schemas import InventoryStatus, Product

from .product_repository import ProductRepository


# Mock 数据移到这里 - 从原来的 product_rec_agent.py 迁移
def _inventory_status(stock: int) -> InventoryStatus:
    if stock <= 0:
        return InventoryStatus.OUT_OF_STOCK
    if stock <= 60:
        return InventoryStatus.LOW_STOCK
    return InventoryStatus.IN_STOCK


def _price_tags(tags: list[str], final_price: float, discount: float, status: InventoryStatus) -> list[str]:
    output: list[str] = []
    if discount > 0:
        output.append("discount")
    if final_price <= 199:
        output.append("value")
    if "新品" in tags:
        output.append("new")
    if status == InventoryStatus.LOW_STOCK:
        output.append("low_stock")
    return output


def _badges(tags: list[str], sales: int, status: InventoryStatus) -> list[str]:
    output: list[str] = []
    if "新品" in tags:
        output.append("new")
    if "旗舰" in tags:
        output.append("flagship")
    if sales >= 6000:
        output.append("hot")
    if status == InventoryStatus.LOW_STOCK:
        output.append("low_stock")
    return output


def _make_product(
    product_id: str,
    name: str,
    category: str,
    price: float,
    *,
    discount: float = 0.0,
    brand: str = "",
    seller_id: str = "S01",
    stock: int = 0,
    tags: list[str] | None = None,
    sales: int = 0,
    rating: float = 0.0,
    review_count: int = 0,
    image_url: str = "",
    external_url: str = "",
    specs: dict | None = None,
) -> Product:
    safe_tags = tags or []
    final_price = round(price - discount, 2) if discount else price
    status = _inventory_status(stock)
    return Product(
        product_id=product_id,
        name=name,
        category=category,
        price=price,
        final_price=final_price,
        discount=discount,
        original_price=price,
        brand=brand,
        seller_id=seller_id,
        stock=stock,
        inventory_status=status,
        sales=sales,
        rating=rating,
        review_count=review_count,
        tags=safe_tags,
        price_tags=_price_tags(safe_tags, final_price, discount, status),
        badges=_badges(safe_tags, sales, status),
        image_url=image_url,
        external_url=external_url,
        specs=specs or {},
        score=rating,
    )


MOCK_PRODUCTS = [
    _make_product(
        "P001",
        "iPhone 16 Pro",
        "手机",
        7999,
        discount=500,
        brand="Apple",
        stock=520,
        tags=["旗舰", "新品"],
        sales=9800,
        rating=4.9,
        review_count=18234,
        external_url="https://example.com/products/P001",
        specs={"storage": "256GB", "color": "Titanium"},
    ),
    _make_product(
        "P002",
        "华为 Mate 70",
        "手机",
        5999,
        discount=300,
        brand="华为",
        stock=340,
        tags=["旗舰", "国产"],
        sales=7600,
        rating=4.7,
        review_count=12980,
        external_url="https://example.com/products/P002",
        specs={"storage": "256GB", "color": "雅黑"},
    ),
    _make_product(
        "P003",
        "小米 15",
        "手机",
        3999,
        discount=200,
        brand="小米",
        stock=880,
        tags=["性价比", "新品"],
        sales=6800,
        rating=4.6,
        review_count=9040,
    ),
    _make_product(
        "P004",
        "Samsung Galaxy S26",
        "手机",
        6999,
        discount=400,
        brand="Samsung",
        stock=210,
        tags=["旗舰"],
        sales=5200,
        rating=4.5,
        review_count=6120,
    ),
    _make_product(
        "P005",
        "OnePlus 13",
        "手机",
        4299,
        discount=180,
        brand="OnePlus",
        stock=460,
        tags=["游戏", "快充"],
        sales=4100,
        rating=4.4,
        review_count=3880,
    ),
    _make_product(
        "P006",
        "AirPods Pro 3",
        "耳机",
        1899,
        discount=150,
        brand="Apple",
        stock=1200,
        tags=["降噪", "无线", "新品"],
        sales=8600,
        rating=4.8,
        review_count=14220,
    ),
    _make_product(
        "P007",
        "Sony WH-1000XM6",
        "耳机",
        2499,
        discount=280,
        brand="Sony",
        stock=260,
        tags=["头戴", "降噪"],
        sales=5200,
        rating=4.7,
        review_count=7040,
    ),
    _make_product(
        "P008",
        "Bose QC Ultra",
        "耳机",
        2299,
        discount=200,
        brand="Bose",
        stock=180,
        tags=["降噪", "舒适"],
        sales=3900,
        rating=4.6,
        review_count=4550,
    ),
    _make_product(
        "P009",
        "Redmi Buds 6 Pro",
        "耳机",
        399,
        discount=80,
        brand="Redmi",
        stock=1600,
        tags=["性价比", "降噪"],
        sales=9200,
        rating=4.5,
        review_count=11780,
    ),
    _make_product(
        "P010",
        "Beats Studio Buds+",
        "耳机",
        1099,
        discount=200,
        brand="Beats",
        stock=420,
        tags=["运动", "无线"],
        sales=3100,
        rating=4.3,
        review_count=2680,
    ),
    _make_product(
        "P011",
        "iPad Air M3",
        "平板",
        4799,
        discount=300,
        brand="Apple",
        stock=440,
        tags=["学习", "办公"],
        sales=5400,
        rating=4.7,
        review_count=7420,
    ),
    _make_product(
        "P012",
        "小米平板 7 Pro",
        "平板",
        2499,
        discount=200,
        brand="小米",
        stock=620,
        tags=["娱乐", "性价比"],
        sales=6700,
        rating=4.5,
        review_count=6650,
    ),
    _make_product(
        "P013",
        "Galaxy Tab S10",
        "平板",
        5499,
        discount=400,
        brand="Samsung",
        stock=240,
        tags=["旗舰", "办公"],
        sales=3600,
        rating=4.4,
        review_count=3020,
    ),
    _make_product(
        "P014",
        "MatePad Pro 13",
        "平板",
        5299,
        discount=480,
        brand="华为",
        stock=260,
        tags=["绘画", "办公"],
        sales=3300,
        rating=4.4,
        review_count=2880,
    ),
    _make_product(
        "P015",
        "联想小新 Pad 2025",
        "平板",
        1999,
        discount=150,
        brand="联想",
        stock=700,
        tags=["学习", "性价比"],
        sales=5200,
        rating=4.3,
        review_count=4120,
    ),
    _make_product(
        "P016",
        "Anker 140W 充电器",
        "配件",
        399,
        discount=60,
        brand="Anker",
        stock=2100,
        tags=["快充", "便携"],
        sales=12000,
        rating=4.8,
        review_count=15600,
    ),
    _make_product(
        "P017",
        "绿联氮化镓 65W",
        "配件",
        129,
        discount=20,
        brand="绿联",
        stock=5200,
        tags=["快充", "性价比"],
        sales=21000,
        rating=4.7,
        review_count=22040,
    ),
    _make_product(
        "P018",
        "倍思 10000mAh 移动电源",
        "配件",
        199,
        discount=30,
        brand="倍思",
        stock=2400,
        tags=["便携", "旅行"],
        sales=9800,
        rating=4.6,
        review_count=9020,
    ),
    _make_product(
        "P019",
        "罗技 MX Master 3S",
        "配件",
        749,
        discount=100,
        brand="Logitech",
        stock=520,
        tags=["无线", "办公"],
        sales=4800,
        rating=4.8,
        review_count=6340,
    ),
    _make_product(
        "P020",
        "Keychron K3 Pro",
        "配件",
        699,
        discount=80,
        brand="Keychron",
        stock=380,
        tags=["机械", "办公"],
        sales=2900,
        rating=4.4,
        review_count=2480,
    ),
    _make_product(
        "P021",
        "MacBook Air M4",
        "笔记本",
        9999,
        discount=800,
        brand="Apple",
        stock=140,
        tags=["轻薄", "办公", "新品"],
        sales=5100,
        rating=4.8,
        review_count=6890,
        specs={"memory": "16GB", "storage": "512GB"},
    ),
    _make_product(
        "P022",
        "Dell XPS 14",
        "笔记本",
        10999,
        discount=900,
        brand="Dell",
        stock=120,
        tags=["旗舰", "办公"],
        sales=3200,
        rating=4.6,
        review_count=3500,
    ),
    _make_product(
        "P023",
        "联想拯救者 Y9000P",
        "笔记本",
        8999,
        discount=700,
        brand="联想",
        stock=210,
        tags=["游戏", "高性能"],
        sales=4300,
        rating=4.5,
        review_count=4120,
    ),
    _make_product(
        "P024",
        "ROG 幻14 2025",
        "笔记本",
        12999,
        discount=1000,
        brand="ASUS",
        stock=90,
        tags=["游戏", "轻薄"],
        sales=2600,
        rating=4.4,
        review_count=2180,
    ),
    _make_product(
        "P025",
        "机械革命 极光 X",
        "笔记本",
        6999,
        discount=500,
        brand="机械革命",
        stock=160,
        tags=["游戏", "性价比"],
        sales=3800,
        rating=4.3,
        review_count=1980,
    ),
    _make_product(
        "P026",
        "戴尔 U2724D 显示器",
        "显示器",
        3299,
        discount=300,
        brand="Dell",
        stock=70,
        tags=["4K", "办公"],
        sales=2200,
        rating=4.6,
        review_count=1550,
    ),
    _make_product(
        "P027",
        "LG 27GP850",
        "显示器",
        2399,
        discount=200,
        brand="LG",
        stock=110,
        tags=["电竞", "高刷"],
        sales=3600,
        rating=4.5,
        review_count=2860,
    ),
    _make_product(
        "P028",
        "AOC 24G2",
        "显示器",
        1099,
        discount=100,
        brand="AOC",
        stock=260,
        tags=["电竞", "性价比"],
        sales=6800,
        rating=4.4,
        review_count=4550,
    ),
    _make_product(
        "P029",
        "华为 MateView SE",
        "显示器",
        1399,
        discount=150,
        brand="华为",
        stock=190,
        tags=["护眼", "办公"],
        sales=3200,
        rating=4.3,
        review_count=1880,
    ),
    _make_product(
        "P030",
        "小米 34 曲面",
        "显示器",
        2199,
        discount=200,
        brand="小米",
        stock=150,
        tags=["大屏", "娱乐"],
        sales=3000,
        rating=4.2,
        review_count=1640,
    ),
    _make_product(
        "P031",
        "三星 990 Pro 2TB",
        "存储",
        1199,
        discount=150,
        brand="三星",
        stock=320,
        tags=["SSD", "高速"],
        sales=5400,
        rating=4.7,
        review_count=4880,
    ),
    _make_product(
        "P032",
        "WD SN850X 1TB",
        "存储",
        799,
        discount=100,
        brand="WD",
        stock=280,
        tags=["SSD", "游戏"],
        sales=4200,
        rating=4.6,
        review_count=3620,
    ),
    _make_product(
        "P033",
        "Kingston NV3 2TB",
        "存储",
        699,
        discount=80,
        brand="Kingston",
        stock=540,
        tags=["SSD", "性价比"],
        sales=6100,
        rating=4.5,
        review_count=4120,
    ),
    _make_product(
        "P034",
        "SanDisk Extreme 1TB",
        "存储",
        699,
        discount=70,
        brand="SanDisk",
        stock=430,
        tags=["便携", "高速"],
        sales=3500,
        rating=4.5,
        review_count=2680,
    ),
    _make_product(
        "P035",
        "希捷 Backup Plus 4TB",
        "存储",
        899,
        discount=120,
        brand="Seagate",
        stock=220,
        tags=["大容量", "备份"],
        sales=2900,
        rating=4.3,
        review_count=1760,
    ),
    _make_product(
        "P036",
        "Apple Watch Ultra 3",
        "穿戴",
        5999,
        discount=500,
        brand="Apple",
        stock=210,
        tags=["运动", "健康"],
        sales=4100,
        rating=4.7,
        review_count=5200,
    ),
    _make_product(
        "P037",
        "华为 Watch GT 6",
        "穿戴",
        1999,
        discount=200,
        brand="华为",
        stock=340,
        tags=["健康", "续航"],
        sales=4700,
        rating=4.5,
        review_count=3920,
    ),
    _make_product(
        "P038",
        "Garmin Fenix 8",
        "穿戴",
        7499,
        discount=600,
        brand="Garmin",
        stock=60,
        tags=["户外", "专业"],
        sales=1800,
        rating=4.6,
        review_count=1280,
    ),
    _make_product(
        "P039",
        "小米 Watch S4",
        "穿戴",
        1299,
        discount=100,
        brand="小米",
        stock=520,
        tags=["性价比", "运动"],
        sales=5200,
        rating=4.4,
        review_count=4020,
    ),
    _make_product(
        "P040",
        "Oura Ring Gen4",
        "穿戴",
        2999,
        discount=300,
        brand="Oura",
        stock=90,
        tags=["睡眠", "健康"],
        sales=1400,
        rating=4.2,
        review_count=860,
    ),
    _make_product(
        "P041",
        "大疆 Mini 4 Pro",
        "无人机",
        4788,
        discount=400,
        brand="大疆",
        stock=120,
        tags=["航拍", "便携"],
        sales=2600,
        rating=4.7,
        review_count=2120,
    ),
    _make_product(
        "P042",
        "大疆 Air 4S",
        "无人机",
        6888,
        discount=500,
        brand="大疆",
        stock=80,
        tags=["航拍", "旗舰"],
        sales=2100,
        rating=4.6,
        review_count=1480,
    ),
    _make_product(
        "P043",
        "Autel EVO Nano+",
        "无人机",
        3599,
        discount=300,
        brand="Autel",
        stock=90,
        tags=["便携", "性价比"],
        sales=1700,
        rating=4.3,
        review_count=820,
    ),
    _make_product(
        "P044",
        "Switch 2",
        "游戏机",
        2499,
        discount=200,
        brand="Nintendo",
        stock=50,
        tags=["新品", "游戏"],
        sales=9000,
        rating=4.8,
        review_count=12100,
    ),
    _make_product(
        "P045",
        "PlayStation 5 Pro",
        "游戏机",
        4499,
        discount=300,
        brand="Sony",
        stock=0,
        tags=["旗舰", "游戏"],
        sales=7400,
        rating=4.7,
        review_count=8650,
    ),
    _make_product(
        "P046",
        "Xbox Series X2",
        "游戏机",
        4299,
        discount=300,
        brand="Microsoft",
        stock=110,
        tags=["游戏", "旗舰"],
        sales=5200,
        rating=4.6,
        review_count=6020,
    ),
    _make_product(
        "P047",
        "Steam Deck OLED",
        "游戏机",
        3799,
        discount=200,
        brand="Valve",
        stock=140,
        tags=["掌机", "游戏"],
        sales=4300,
        rating=4.5,
        review_count=3580,
    ),
    _make_product(
        "P048",
        "海尔 508L 变频冰箱",
        "家电",
        4599,
        discount=500,
        brand="Haier",
        stock=80,
        tags=["大容量", "节能"],
        sales=2400,
        rating=4.5,
        review_count=1680,
    ),
    _make_product(
        "P049",
        "美的 1.5匹 变频空调",
        "家电",
        3299,
        discount=400,
        brand="美的",
        stock=120,
        tags=["静音", "节能"],
        sales=3100,
        rating=4.4,
        review_count=1950,
    ),
    _make_product(
        "P050",
        "小米 全屋智能套装",
        "智能家居",
        1999,
        discount=300,
        brand="小米",
        stock=300,
        tags=["智能", "套装"],
        sales=5200,
        rating=4.6,
        review_count=3380,
    ),
    _make_product(
        "P051",
        "华为 智能门锁 Pro",
        "智能家居",
        1699,
        discount=200,
        brand="华为",
        stock=140,
        tags=["安防", "智能"],
        sales=2800,
        rating=4.5,
        review_count=1820,
    ),
    _make_product(
        "P052",
        "索尼 A7C II",
        "摄影",
        12999,
        discount=800,
        brand="Sony",
        stock=60,
        tags=["旗舰", "全画幅"],
        sales=1500,
        rating=4.7,
        review_count=980,
    ),
    _make_product(
        "P053",
        "佳能 EOS R8",
        "摄影",
        9999,
        discount=700,
        brand="Canon",
        stock=90,
        tags=["轻量", "全画幅"],
        sales=1700,
        rating=4.6,
        review_count=860,
    ),
    _make_product(
        "P054",
        "兄弟 HL-L2350DW 打印机",
        "办公设备",
        1299,
        discount=200,
        brand="Brother",
        stock=160,
        tags=["打印", "办公"],
        sales=2600,
        rating=4.4,
        review_count=1240,
    ),
    _make_product(
        "P055",
        "爱普生 EB-E01 投影仪",
        "办公设备",
        3299,
        discount=300,
        brand="Epson",
        stock=70,
        tags=["会议", "高清"],
        sales=1100,
        rating=4.3,
        review_count=620,
    ),
    _make_product(
        "P056",
        "迪卡侬 跑步手表",
        "运动户外",
        999,
        discount=100,
        brand="Decathlon",
        stock=260,
        tags=["运动", "户外"],
        sales=2100,
        rating=4.3,
        review_count=880,
    ),
    _make_product(
        "P057",
        "北面 三合一冲锋衣",
        "运动户外",
        1899,
        discount=200,
        brand="TheNorthFace",
        stock=120,
        tags=["户外", "保暖"],
        sales=1900,
        rating=4.4,
        review_count=760,
    ),
    _make_product(
        "P058",
        "Samsung Galaxy S24 Ultra",
        "手机",
        9999,
        discount=500,
        brand="Samsung",
        stock=120,
        tags=["旗舰", "影像", "新品"],
        sales=5400,
        rating=4.7,
        review_count=3200,
    ),
    _make_product(
        "P059",
        "Google Pixel 8 Pro",
        "手机",
        7999,
        discount=400,
        brand="Google",
        stock=90,
        tags=["旗舰", "影像"],
        sales=2600,
        rating=4.6,
        review_count=1800,
    ),
    _make_product(
        "P060",
        "OPPO Find X7 Ultra",
        "手机",
        5999,
        discount=300,
        brand="OPPO",
        stock=200,
        tags=["旗舰", "影像"],
        sales=4300,
        rating=4.6,
        review_count=2500,
    ),
    _make_product(
        "P061",
        "vivo X100 Pro",
        "手机",
        5499,
        discount=300,
        brand="vivo",
        stock=220,
        tags=["影像", "旗舰"],
        sales=3900,
        rating=4.5,
        review_count=2300,
    ),
    _make_product(
        "P062",
        "荣耀 Magic6 Pro",
        "手机",
        5699,
        discount=300,
        brand="荣耀",
        stock=240,
        tags=["旗舰", "护眼"],
        sales=3500,
        rating=4.5,
        review_count=2100,
    ),
    _make_product(
        "P063",
        "iPad Pro 11 (M4)",
        "平板",
        8999,
        discount=500,
        brand="Apple",
        stock=130,
        tags=["旗舰", "办公", "新品"],
        sales=4200,
        rating=4.8,
        review_count=2600,
    ),
    _make_product(
        "P064",
        "iPad Air 11 (M2)",
        "平板",
        4799,
        discount=300,
        brand="Apple",
        stock=200,
        tags=["办公", "学习"],
        sales=3800,
        rating=4.7,
        review_count=2300,
    ),
    _make_product(
        "P065",
        "Galaxy Tab S9",
        "平板",
        5299,
        discount=400,
        brand="Samsung",
        stock=150,
        tags=["旗舰", "办公"],
        sales=2400,
        rating=4.6,
        review_count=1500,
    ),
    _make_product(
        "P066",
        "华为 MatePad Air",
        "平板",
        3299,
        discount=300,
        brand="华为",
        stock=180,
        tags=["学习", "办公"],
        sales=2600,
        rating=4.5,
        review_count=1700,
    ),
    _make_product(
        "P067",
        "Redmi Pad SE",
        "平板",
        1299,
        discount=100,
        brand="Redmi",
        stock=420,
        tags=["性价比", "娱乐"],
        sales=5600,
        rating=4.4,
        review_count=3100,
    ),
    _make_product(
        "P068",
        "Sony WH-1000XM5",
        "耳机",
        2999,
        discount=300,
        brand="Sony",
        stock=160,
        tags=["降噪", "头戴", "旗舰"],
        sales=3600,
        rating=4.7,
        review_count=2200,
    ),
    _make_product(
        "P069",
        "Bose QuietComfort Ultra",
        "耳机",
        3299,
        discount=400,
        brand="Bose",
        stock=120,
        tags=["降噪", "舒适", "旗舰"],
        sales=2800,
        rating=4.6,
        review_count=1700,
    ),
    _make_product(
        "P070",
        "AirPods Pro (2nd Gen)",
        "耳机",
        1999,
        discount=200,
        brand="Apple",
        stock=260,
        tags=["降噪", "无线", "旗舰"],
        sales=5200,
        rating=4.8,
        review_count=4100,
    ),
    _make_product(
        "P071",
        "Sennheiser Momentum 4",
        "耳机",
        2699,
        discount=300,
        brand="Sennheiser",
        stock=140,
        tags=["降噪", "音乐"],
        sales=1900,
        rating=4.5,
        review_count=980,
    ),
    _make_product(
        "P072",
        "Sony WF-1000XM5",
        "耳机",
        2199,
        discount=200,
        brand="Sony",
        stock=200,
        tags=["降噪", "真无线"],
        sales=2700,
        rating=4.6,
        review_count=1500,
    ),
    _make_product(
        "P073",
        "Apple 35W 双口充电器",
        "配件",
        269,
        discount=40,
        brand="Apple",
        stock=800,
        tags=["快充", "便携"],
        sales=8200,
        rating=4.6,
        review_count=5200,
    ),
    _make_product(
        "P074",
        "绿联 7合1 USB-C Hub",
        "配件",
        329,
        discount=50,
        brand="绿联",
        stock=600,
        tags=["办公", "扩展"],
        sales=5100,
        rating=4.5,
        review_count=2600,
    ),
    _make_product(
        "P075",
        "Anker 240W Type-C 数据线",
        "配件",
        129,
        discount=20,
        brand="Anker",
        stock=1200,
        tags=["快充", "耐用"],
        sales=7200,
        rating=4.6,
        review_count=4100,
    ),
    _make_product(
        "P076",
        "罗技 C920 高清摄像头",
        "配件",
        499,
        discount=80,
        brand="Logitech",
        stock=320,
        tags=["办公", "直播"],
        sales=2600,
        rating=4.5,
        review_count=1800,
    ),
    _make_product(
        "P077",
        "SanDisk Extreme Pro 128GB UHS-I",
        "配件",
        199,
        discount=30,
        brand="SanDisk",
        stock=900,
        tags=["高速", "便携"],
        sales=6100,
        rating=4.6,
        review_count=3000,
    ),
    _make_product(
        "P078",
        "HP Spectre x360 14",
        "笔记本",
        10999,
        discount=900,
        brand="HP",
        stock=90,
        tags=["旗舰", "轻薄", "办公"],
        sales=1800,
        rating=4.5,
        review_count=900,
    ),
    _make_product(
        "P079",
        "ThinkPad X1 Carbon Gen 12",
        "笔记本",
        12999,
        discount=1000,
        brand="Lenovo",
        stock=80,
        tags=["旗舰", "商务", "办公"],
        sales=2100,
        rating=4.6,
        review_count=1100,
    ),
    _make_product(
        "P080",
        "ASUS Zenbook 14 OLED",
        "笔记本",
        7999,
        discount=700,
        brand="ASUS",
        stock=140,
        tags=["轻薄", "办公"],
        sales=2600,
        rating=4.5,
        review_count=1500,
    ),
    _make_product(
        "P081",
        "Surface Laptop 6",
        "笔记本",
        8999,
        discount=800,
        brand="Microsoft",
        stock=120,
        tags=["轻薄", "办公"],
        sales=1900,
        rating=4.4,
        review_count=880,
    ),
    _make_product(
        "P082",
        "Acer Swift Go 14",
        "笔记本",
        5999,
        discount=500,
        brand="Acer",
        stock=160,
        tags=["性价比", "轻薄"],
        sales=2300,
        rating=4.3,
        review_count=1020,
    ),
    _make_product(
        "P083",
        "Dell U2723QE",
        "显示器",
        4599,
        discount=400,
        brand="Dell",
        stock=90,
        tags=["4K", "办公", "旗舰"],
        sales=1900,
        rating=4.6,
        review_count=950,
    ),
    _make_product(
        "P084",
        "LG 32UN880",
        "显示器",
        3999,
        discount=300,
        brand="LG",
        stock=100,
        tags=["4K", "护眼"],
        sales=1600,
        rating=4.5,
        review_count=820,
    ),
    _make_product(
        "P085",
        "Samsung Odyssey G7 27",
        "显示器",
        3499,
        discount=300,
        brand="Samsung",
        stock=110,
        tags=["电竞", "高刷"],
        sales=2400,
        rating=4.5,
        review_count=1100,
    ),
    _make_product(
        "P086",
        "ASUS ProArt PA278CV",
        "显示器",
        2699,
        discount=200,
        brand="ASUS",
        stock=130,
        tags=["专业", "办公"],
        sales=1500,
        rating=4.4,
        review_count=760,
    ),
    _make_product(
        "P087",
        "小米 27 2K 电竞显示器",
        "显示器",
        1799,
        discount=200,
        brand="小米",
        stock=200,
        tags=["电竞", "性价比"],
        sales=3200,
        rating=4.4,
        review_count=1800,
    ),
    _make_product(
        "P088",
        "Samsung T7 Shield 1TB",
        "存储",
        799,
        discount=100,
        brand="Samsung",
        stock=260,
        tags=["便携", "高速"],
        sales=2200,
        rating=4.6,
        review_count=1300,
    ),
    _make_product(
        "P089",
        "Crucial MX500 1TB",
        "存储",
        599,
        discount=80,
        brand="Crucial",
        stock=340,
        tags=["SSD", "性价比"],
        sales=2800,
        rating=4.5,
        review_count=1600,
    ),
    _make_product(
        "P090",
        "Seagate FireCuda 530 1TB",
        "存储",
        899,
        discount=120,
        brand="Seagate",
        stock=200,
        tags=["SSD", "高速"],
        sales=1900,
        rating=4.6,
        review_count=980,
    ),
    _make_product(
        "P091",
        "WD Elements 2TB",
        "存储",
        499,
        discount=60,
        brand="WD",
        stock=380,
        tags=["大容量", "便携"],
        sales=2600,
        rating=4.4,
        review_count=1400,
    ),
    _make_product(
        "P092",
        "Lexar NM790 1TB",
        "存储",
        599,
        discount=80,
        brand="Lexar",
        stock=320,
        tags=["SSD", "游戏"],
        sales=2400,
        rating=4.5,
        review_count=1200,
    ),
    _make_product(
        "P093",
        "Apple Watch Series 10",
        "穿戴",
        3299,
        discount=300,
        brand="Apple",
        stock=180,
        tags=["健康", "新品"],
        sales=2800,
        rating=4.7,
        review_count=1600,
    ),
    _make_product(
        "P094",
        "Galaxy Watch 7",
        "穿戴",
        2499,
        discount=250,
        brand="Samsung",
        stock=160,
        tags=["健康", "运动"],
        sales=2100,
        rating=4.5,
        review_count=1200,
    ),
    _make_product(
        "P095",
        "华为 Watch 4 Pro",
        "穿戴",
        3499,
        discount=300,
        brand="华为",
        stock=140,
        tags=["旗舰", "健康"],
        sales=1900,
        rating=4.5,
        review_count=980,
    ),
    _make_product(
        "P096",
        "Garmin Venu 3",
        "穿戴",
        2799,
        discount=300,
        brand="Garmin",
        stock=120,
        tags=["运动", "专业"],
        sales=1600,
        rating=4.6,
        review_count=780,
    ),
    _make_product(
        "P097",
        "小米手环 9 Pro",
        "穿戴",
        399,
        discount=50,
        brand="小米",
        stock=600,
        tags=["性价比", "运动", "新品"],
        sales=5200,
        rating=4.4,
        review_count=3200,
    ),
    _make_product(
        "P098",
        "DJI Mavic 3 Classic",
        "无人机",
        8999,
        discount=700,
        brand="DJI",
        stock=90,
        tags=["航拍", "旗舰"],
        sales=1400,
        rating=4.7,
        review_count=720,
    ),
    _make_product(
        "P099",
        "DJI Avata 2",
        "无人机",
        6999,
        discount=600,
        brand="DJI",
        stock=80,
        tags=["FPV", "新品"],
        sales=1200,
        rating=4.6,
        review_count=640,
    ),
    _make_product(
        "P100",
        "DJI Neo",
        "无人机",
        1999,
        discount=200,
        brand="DJI",
        stock=200,
        tags=["便携", "新品"],
        sales=2200,
        rating=4.4,
        review_count=900,
    ),
    _make_product(
        "P101",
        "Autel EVO Lite+",
        "无人机",
        7999,
        discount=600,
        brand="Autel",
        stock=70,
        tags=["航拍", "旗舰"],
        sales=900,
        rating=4.4,
        review_count=420,
    ),
    _make_product(
        "P102",
        "Skydio 2+",
        "无人机",
        9999,
        discount=800,
        brand="Skydio",
        stock=50,
        tags=["智能", "旗舰"],
        sales=600,
        rating=4.3,
        review_count=300,
    ),
    _make_product(
        "P103",
        "PlayStation 5 Slim",
        "游戏机",
        3499,
        discount=300,
        brand="Sony",
        stock=140,
        tags=["游戏", "新品"],
        sales=5200,
        rating=4.7,
        review_count=3100,
    ),
    _make_product(
        "P104",
        "Xbox Series S",
        "游戏机",
        2199,
        discount=200,
        brand="Microsoft",
        stock=180,
        tags=["游戏", "性价比"],
        sales=3800,
        rating=4.5,
        review_count=2200,
    ),
    _make_product(
        "P105",
        "Nintendo Switch OLED",
        "游戏机",
        2499,
        discount=200,
        brand="Nintendo",
        stock=160,
        tags=["游戏", "掌机"],
        sales=4600,
        rating=4.6,
        review_count=2600,
    ),
    _make_product(
        "P106",
        "ASUS ROG Ally",
        "游戏机",
        3999,
        discount=300,
        brand="ASUS",
        stock=120,
        tags=["掌机", "旗舰"],
        sales=2100,
        rating=4.4,
        review_count=980,
    ),
    _make_product(
        "P107",
        "Logitech G Cloud",
        "游戏机",
        2499,
        discount=200,
        brand="Logitech",
        stock=100,
        tags=["掌机", "云游戏"],
        sales=1400,
        rating=4.3,
        review_count=760,
    ),
    _make_product(
        "P108",
        "美的 60L 电热水器",
        "家电",
        1199,
        discount=150,
        brand="美的",
        stock=180,
        tags=["节能", "家用"],
        sales=2600,
        rating=4.4,
        review_count=1400,
    ),
    _make_product(
        "P109",
        "海尔 10kg 洗衣机",
        "家电",
        2499,
        discount=300,
        brand="Haier",
        stock=120,
        tags=["大容量", "家用"],
        sales=2100,
        rating=4.5,
        review_count=1280,
    ),
    _make_product(
        "P110",
        "格力 1.5匹 变频空调",
        "家电",
        3799,
        discount=400,
        brand="格力",
        stock=110,
        tags=["节能", "静音"],
        sales=1900,
        rating=4.5,
        review_count=1100,
    ),
    _make_product(
        "P111",
        "小米 扫拖机器人 X10",
        "家电",
        2599,
        discount=300,
        brand="小米",
        stock=160,
        tags=["智能", "清洁"],
        sales=2300,
        rating=4.4,
        review_count=1500,
    ),
    _make_product(
        "P112",
        "松下 蒸烤一体机",
        "家电",
        2999,
        discount=350,
        brand="Panasonic",
        stock=90,
        tags=["厨房", "品质"],
        sales=900,
        rating=4.4,
        review_count=520,
    ),
    _make_product(
        "P113",
        "小米 智能音箱 Pro",
        "智能家居",
        399,
        discount=50,
        brand="小米",
        stock=420,
        tags=["智能", "语音"],
        sales=5200,
        rating=4.5,
        review_count=2600,
    ),
    _make_product(
        "P114",
        "华为 路由器 AX3 Pro",
        "智能家居",
        299,
        discount=40,
        brand="华为",
        stock=380,
        tags=["高速", "智能"],
        sales=4100,
        rating=4.4,
        review_count=2100,
    ),
    _make_product(
        "P115",
        "Aqara 智能开关 H1",
        "智能家居",
        199,
        discount=30,
        brand="Aqara",
        stock=500,
        tags=["智能", "家居"],
        sales=3600,
        rating=4.5,
        review_count=1800,
    ),
    _make_product(
        "P116",
        "TP-Link Kasa 智能插座",
        "智能家居",
        129,
        discount=20,
        brand="TP-Link",
        stock=600,
        tags=["智能", "便捷"],
        sales=3300,
        rating=4.4,
        review_count=1700,
    ),
    _make_product(
        "P117",
        "海康威视 智能摄像头 C6",
        "智能家居",
        299,
        discount=30,
        brand="海康威视",
        stock=420,
        tags=["安防", "智能"],
        sales=2700,
        rating=4.3,
        review_count=1200,
    ),
    _make_product(
        "P118",
        "Sony FX30",
        "摄影",
        12999,
        discount=800,
        brand="Sony",
        stock=70,
        tags=["专业", "旗舰"],
        sales=800,
        rating=4.7,
        review_count=420,
    ),
    _make_product(
        "P119",
        "Canon EOS R6 Mark II",
        "摄影",
        15999,
        discount=1000,
        brand="Canon",
        stock=60,
        tags=["旗舰", "全画幅"],
        sales=900,
        rating=4.8,
        review_count=380,
    ),
    _make_product(
        "P120",
        "Nikon Z6 II",
        "摄影",
        12999,
        discount=900,
        brand="Nikon",
        stock=80,
        tags=["全画幅", "专业"],
        sales=700,
        rating=4.6,
        review_count=320,
    ),
    _make_product(
        "P121",
        "Fujifilm X-T5",
        "摄影",
        13999,
        discount=900,
        brand="Fujifilm",
        stock=70,
        tags=["旗舰", "轻量"],
        sales=650,
        rating=4.6,
        review_count=300,
    ),
    _make_product(
        "P122",
        "DJI Osmo Pocket 3",
        "摄影",
        3499,
        discount=300,
        brand="DJI",
        stock=200,
        tags=["便携", "视频"],
        sales=2100,
        rating=4.6,
        review_count=1000,
    ),
    _make_product(
        "P123",
        "惠普 LaserJet Pro M404dn",
        "办公设备",
        2499,
        discount=300,
        brand="HP",
        stock=90,
        tags=["办公", "打印"],
        sales=1600,
        rating=4.4,
        review_count=720,
    ),
    _make_product(
        "P124",
        "富士施乐 DocuPrint P285dw",
        "办公设备",
        1399,
        discount=200,
        brand="富士施乐",
        stock=130,
        tags=["打印", "办公"],
        sales=1500,
        rating=4.3,
        review_count=680,
    ),
    _make_product(
        "P125",
        "兄弟 MFC-L2710DW 一体机",
        "办公设备",
        1799,
        discount=250,
        brand="Brother",
        stock=110,
        tags=["打印", "办公"],
        sales=1400,
        rating=4.4,
        review_count=640,
    ),
    _make_product(
        "P126",
        "爱普生 EB-FH52 投影仪",
        "办公设备",
        3299,
        discount=300,
        brand="Epson",
        stock=60,
        tags=["会议", "高清"],
        sales=800,
        rating=4.3,
        review_count=360,
    ),
    _make_product(
        "P127",
        "得力 9920 碎纸机",
        "办公设备",
        899,
        discount=120,
        brand="得力",
        stock=180,
        tags=["办公", "安全"],
        sales=1300,
        rating=4.3,
        review_count=520,
    ),
    _make_product(
        "P128",
        "Garmin Forerunner 965",
        "运动户外",
        4499,
        discount=400,
        brand="Garmin",
        stock=90,
        tags=["运动", "专业"],
        sales=1100,
        rating=4.6,
        review_count=520,
    ),
    _make_product(
        "P129",
        "迪卡侬 2秒帐篷",
        "运动户外",
        699,
        discount=80,
        brand="迪卡侬",
        stock=240,
        tags=["露营", "户外"],
        sales=2600,
        rating=4.4,
        review_count=1400,
    ),
    _make_product(
        "P130",
        "始祖鸟 Beta LT 冲锋衣",
        "运动户外",
        2999,
        discount=300,
        brand="Arc'teryx",
        stock=70,
        tags=["户外", "保暖"],
        sales=900,
        rating=4.5,
        review_count=420,
    ),
    _make_product(
        "P131",
        "Salomon 徒步鞋 XA Pro 3D",
        "运动户外",
        1299,
        discount=150,
        brand="Salomon",
        stock=120,
        tags=["户外", "徒步"],
        sales=1200,
        rating=4.4,
        review_count=480,
    ),
    _make_product(
        "P132",
        "Black Diamond Spot 400 头灯",
        "运动户外",
        499,
        discount=60,
        brand="BlackDiamond",
        stock=180,
        tags=["户外", "便携"],
        sales=1500,
        rating=4.3,
        review_count=600,
    ),
]


class InMemoryProductRepository(ProductRepository):
    """
    内存实现 - 用于开发和降级场景

    特点:
    - 使用静态 Mock 数据
    - 所有操作在内存中完成
    - 不会抛出异常，只返回空列表
    """

    def __init__(self, products: list[Product] | None = None):
        self._products = products if products is not None else list(MOCK_PRODUCTS)
        self._id_index = {p.product_id: p for p in self._products}
        self._category_index: dict[str, list[Product]] = {}
        for p in self._products:
            if p.category not in self._category_index:
                self._category_index[p.category] = []
            self._category_index[p.category].append(p)

    async def get_by_ids(self, ids: list[str]) -> list[Product]:
        """根据 ID 批量查询"""
        return [self._id_index[id_] for id_ in ids if id_ in self._id_index]

    async def get_by_category(self, category: str, limit: int = 10) -> list[Product]:
        """按类目查询"""
        products = self._category_index.get(category, [])
        return products[:limit]

    async def get_by_price_range(
        self, min_price: float, max_price: float, limit: int = 10
    ) -> list[Product]:
        """按价格区间查询"""
        products = [
            p for p in self._products if min_price <= p.price <= max_price
        ]
        return products[:limit]

    async def get_hot_products(self, limit: int = 10) -> list[Product]:
        """
        获取热门商品

        简化实现：按 stock 降序模拟热度
        生产环境可按销量/访问量排序
        """
        sorted_products = sorted(
            self._products, key=lambda p: (p.sales, p.stock), reverse=True
        )
        return sorted_products[:limit]

    async def get_new_products(self, limit: int = 10) -> list[Product]:
        """
        获取新品

        简化实现：按 tags 包含"新品"筛选
        生产环境可按上架时间排序
        """
        new_products = [p for p in self._products if "新品" in p.tags]
        return new_products[:limit]

    async def get_all_products(self, limit: int = 100) -> list[Product]:
        """获取所有商品"""
        return self._products[:limit]
